theme: jekyll-theme-tactile
title: Osnove Programiranja
description: Osnove programiranja kroz programski jezik C
sidebars:
  - label: Section One
    children:
      - document-one
      - document-two
      - document-three
