theme: jekyll-theme-minimal
title: PROJECT:CLASSROOM
description: Osnove programiranja kroz programski jezik C
sidebars:
  - home-page
  - label: Section One
    children:
      - document-one
      - document-two
      - document-three
